### ISSUE TITLE
java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by Protheus** [TotalHamman/BetterBlockExchanger#7]
**Version:**
MC 1.10.2
Forge: 2221
betterblockexchanger-1.10.2-0.5a

**What happend:**
- Created the wand
- Shift rightclick on Diorite block
- Game crash

**Pastebin:**
http://pastebin.com/Cp0kymWZ

**Short:**
WARNING: coremods are present:
  LoadingHook (Mekanism-1.10.2-9.2.1.298.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.2.205-universal.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.3.82-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.2.114-universal.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.2.10.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.339.jar)
  MalisisSwitchesPlugin (malisisswitches-1.10.2-3.1.0.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 23/01/17 12:01
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:507)
	at totalhamman.betterblockexchanger.handlers.BlockExchangeHandler.getBlockName(BlockExchangeHandler.java:309)
	at totalhamman.betterblockexchanger.items.ItemExchanger.func_77624_a(ItemExchanger.java:84)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:614)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:136)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:166)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TotalHamman** [comment]
Did you add the mod to a pre-made pack or a custom one?  Just to make it easier for me to try and reproduce the error.

**Comment by Protheus** [comment]
This is my custom modpack

**Comment by TotalHamman** [comment]
Accidentally selected the wrong hunk when closing initially.

**Comment by Protheus** [comment]
Will check when a new release is available

**Comment by TotalHamman** [comment]
The release is available now on CurseForge. Enjoy :D

https://minecraft.curseforge.com/projects/better-block-exchanger/files/2372419

**Comment by Protheus** [comment]
Working perfect 😀
